DATA SEGMENT
A DB 20H,21H,22H,19H,08H,13H,24H,35H,45H,56H
B DB ?
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
MOV AX,DATA
MOV DS,AX
LEA SI,A
MOV AL,[SI]
MOV CX,9
BACK:
        CMP AL,[SI+1]
        JC DOWN
        MOV AL,[SI+1]
        DOWN: INC SI
        LOOP BACK
        MOV B,AL
        MOV AH,4CH
        INT 21H
        CODE ENDS
        END START
